inherit_from: .rubocop_todo.yml

Style/SignalException:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesignalexception

Style/RegexpLiteral:
  MaxSlashes: 0

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 42

Metrics/PerceivedComplexity:
  Max: 12

