# This is an example of the main configuration file for catflap.
# By default catflap looks for this file in /usr/local/etc/catflap/config.yaml
# but you can change the location by using the --config-file <filepath> option
# of the bin/catflap command line interface.

server:
  listen_addr: '0.0.0.0' # what ip address the catflap server should listen on.
  port: 8778 # the TCP port that the catflap server listens to.
  docroot: './ui' # you can override the ui location.
  endpoint: '/catflap' # the endpoint for the REST API.
  passfile: './etc/passfile.yaml' # pass phrases are stored here.
  token_ttl: 15 # expire tokens after 15 seconds.
  pid_path: '/var/run' # The path where the pid file should be written.

  https:
    port: 4773 # TCP oport that catflap https server listens to.
    force: true # Force HTTP requests to redirect to HTTPS.
    certificate: false # Path to your SSL certificate file.
    private_key: false # Private key for your SSL certificate.

firewall:
  plugin: 'netfilter' # options are netfilter or iptables
  dports: '80,443' # lock multiple ports separating them by commas.
  options: # options are specific to each firewall plugin driver.
    chain: 'CATFLAP' # Namespace for the chains (e.g. CATFLAP-ALLOW, CATFLAP-DENY).
    log_rejected: true
    accept_local: false # this is only set to false only when devs are testing catflap.
